### ISSUE TITLE
radar-config ordering not consistent with how it's displayed

### ISSUE THREAD

**Issue by nilsmull** [Bonial-International-GmbH/MkRadar#3]
The ordering of pages in the radar-config isn't the same how it is displayed on the page.
e.g.:
```yaml
  -
    category: Kubernetes
    title: "workshop1"
    type: "private"
    url: "https://bitbucket.org/bonialgroup/k8s-terraform/src/master/workshops/kubernetes-1/README.md"
  -
    category: Kubernetes
    title: "workshop2"
    type: "private"
    url: "https://bitbucket.org/bonialgroup/k8s-terraform/src/master/workshops/kubernetes-2/README.md"
  -
    category: Kubernetes
    title: "workshop3"
    type: "private"
    url: "https://bitbucket.org/bonialgroup/k8s-terraform/src/master/workshops/kubernetes-3/README.md"
```
is displayed as:
Kubernetes --> 
   - workshop3
   - workshop1
   - workshpp2
