### ISSUE TITLE
Support for sub-catergories

### ISSUE THREAD

**Issue by nilsmull** [Bonial-International-GmbH/MkRadar#4]
It would be helpful to sub structure the categories. As a proposal here a radar-config:
```yaml
---
version: "1"
categories:
  - title: GeneralDevOps
    pages:
      - title: site24*7
        type: public
        notification: false
        tags: "terraform, go, shell"
        url: "https://github.com/Bonial-International-GmbH/terraform-provider-site24x7/blob/master/README.md"
      - title: "Terraform Dead Man's Snitch Provider"
        type: public
        url: "https://github.com/Bonial-International-GmbH/terraform-provider-dmsnitch/blob/master/README.md"
      - title: "MkRadar"
        type: public
        url: "https://github.com/Bonial-International-GmbH/MkRadar/blob/main/README.md"
  - title: Kubernetes
    categories:
      - title: 'workshops'
        pages:
          - title: "docker"
            type: "private"
            url: "https://bitbucket.org/bonialgroup/k8s-terraform/src/master/workshops/docker/README.md"
          - title: "workshop1"
            type: "private"
            url: "https://bitbucket.org/bonialgroup/k8s-terraform/src/master/workshops/kubernetes-1/README.md"
    pages:
      - title: "k8s-terraform"
        type: "private"
        url: "https://bitbucket.org/bonialgroup/k8s-terraform/src/master/README.md"
```

Pay attention to the category with the title Kubernetes. It can contain pages and categories.
